# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 expandtab:

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu_aws"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  config.vm.hostname = "LicenseServer"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY']
    aws.secret_access_key = ENV['AWS_SECRET_KEY']

    aws.instance_type = "t2.micro"
    aws.keypair_name = ENV['AWS_KEYPAIR_NAME'] 

    aws.ami = "ami-f95ef58a"
    aws.region = "eu-west-1"
    aws.subnet_id = "subnet-ce360f97"
    aws.tags = {
      'Name' => 'SoftwareDevLic',
    }

    aws.security_groups = ['sg-db4250bf']

    aws.ssh_host_attribute = :private_ip_address
    aws.private_ip_address = '10.0.0.12'

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = ENV['PRIVATE_AWS_SSH_KEY_PATH']
    override.ssh.proxy_command = "ssh -A ubuntu@dev.zenotech.com -W %h:%p"
  end

  # Provision
#  config.vm.provision "ansible" do |ansible|
#    ansible.playbook = "provisioning/provision.yml"
#  end
end

