# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 expandtab:

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos_aws"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY']
    aws.secret_access_key = ENV['AWS_SECRET_KEY']
    #aws.instance_type = "m4.large"
    aws.instance_type = "t2.micro"
    aws.keypair_name = ENV['AWS_KEYPAIR_NAME'] 
    aws.ami = "ami-a7d155d4"
    aws.region = "eu-west-1"
    aws.tags = {
      'Name' => 'Centos-7.2-SoftwareDev',
    }
    aws.ssh_host_attribute = :private_ip_address
    aws.security_groups = ['sg-8c0db7e8']

    aws.subnet_id = "subnet-ef2910b6"
    aws.private_ip_address = '10.0.3.10'

    aws.region_config "eu-west-1" do |region|
        region.spot_instance = true
        region.spot_max_price = "0.03"
    end

    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = ENV['PRIVATE_AWS_SSH_KEY_PATH']
    override.ssh.proxy_command = "ssh -A ubuntu@dev.zenotech.com -W %h:%p"
  end

end

