# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 expandtab:

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "nat_aws"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY']
    aws.secret_access_key = ENV['AWS_SECRET_KEY']
    #aws.instance_type = "m4.large"
    aws.instance_type = "t2.micro"
    aws.keypair_name = ENV['AWS_KEYPAIR_NAME'] 
    # Use amazon nat ami
    aws.ami = "ami-555ce426"
    aws.region = "eu-west-1"
    # Public subnet
    aws.subnet_id = "subnet-ce360f97"

    aws.tags = {
      'Name' => 'SoftwareDevNAT'
    }
    aws.security_groups = ['sg-36415152']

    aws.ssh_host_attribute = :private_ip_address
    aws.associate_public_ip = true
    aws.private_ip_address = '10.0.0.11'

    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = ENV['PRIVATE_AWS_SSH_KEY_PATH']
    override.ssh.proxy_command = "ssh -A ubuntu@dev.zenotech.com -W %h:%p"
  end

  # Provision
  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "provisioning/site.yml"
  #end

  # Need to add route to NAT in SoftwareDevPrivate routing table

end

