---
galaxy_info:
  author: Mark Wilde
  description: An Ansible role for installing GNU C compiler.
  license: MIT
  min_ansible_version: 1.9
  platforms:
    - name: EL
      versions:
        - 6
    - name: Ubuntu
      versions:
        - trusty
  categories:
    - development
