---
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: "debian/main.yml"
  when: ansible_os_family == 'Debian'

- include: "redhat/main.yml"
  when: ansible_os_family == 'RedHat'
