---
ansible:
  verbose:
  sudo: True
  group_vars:
    all:
      - pip_version: "*"

vagrant:
  platforms:
    - name: trusty64
      box: ubuntu/trusty64

    - name: xenial64
      box: ubuntu/xenial64

  providers:
    - name: virtualbox
      type: virtualbox

  instances:
    - name: ansible-pip