---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-fail2ban"
  git_branch: "master"
  galaxy_id: '3377'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    [fail2ban](http://www.fail2ban.org/) is a service which parses specified
    log files and can perform configured actions when a given regexp is found.
    It's usually used to ban offending IP addresses using `iptables` rules
    (only IPv4 connections are supported at the moment).

