---
- hosts: ci-slave
  sudo: yes
  pre_tasks:
    - name: "Update apt cache if needed"
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == 'Debian'

  roles:
        - awailly.cis-ubuntu-ansible
        - geerlingguy.java
        - geerlingguy.git
        - wldpua2008.vagrant
        - kbrebanov.packer
