---
- include: harden.yml
- hosts: all
  become: yes
  become_user: root
  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Install libselinux-python
      package: pkg={{item}} state=latest
      with_items:
        - libselinux-python
- hosts: all
  become: yes
  become_user: root
  roles:
        - geerlingguy.git
        - kfieldho.cmake
  tasks:
    - name: redhat | Install scl and devpackages
      package: pkg={{item}} state=latest
      with_items:
        - centos-release-scl
        - flex
        - bison
        - libX11-devel
        - rpm-build
        - libtool
        - kernel-devel
        - numactl-devel
        - wget
        - tcl-devel
        - gtest-devel
        - texlive-latex
        - ImageMagick
        - sqlite-devel
        - poppler-utils
        - latex2html
        - nfs-utils
        - bind-utils
      when: ansible_os_family == 'RedHat'
    - name: Install cuda repo
      yum: state=present pkg=http://developer.download.nvidia.com/compute/cuda/repos/rhel6/x86_64/cuda-repo-rhel6-9.1.85-1.x86_64.rpm
      when: ansible_os_family == 'RedHat'
    - name: redhat | Install devtoolset, git and cuda
      package: pkg={{item}} state=latest
      with_items:
        - devtoolset-3-toolchain
        - devtoolset-4-toolchain
        - devtoolset-6-toolchain
        - cuda
        - rh-git29
      when: ansible_os_family == 'RedHat'
    - name: Download intel 2016.3 installer
      get_url: url=http://packages.zenotech.com/parallel_studio_xe_2016_update3_online.sh dest=/tmp/intel_installer_online.sh mode=0755
    - name: Download silent.cfg
      get_url: url=http://packages.zenotech.com/silent.cfg dest=/tmp/silent.cfg mode=0644
    - name: Install intel toolset
      command: /tmp/intel_installer_online.sh --silent /tmp/silent.cfg
      tags: intel
