---
- include: harden.yml
- hosts: all
  become: yes
  become_user: root
  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Install libselinux-python
      package: pkg={{item}} state=latest
      with_items:
        - libselinux-python
- hosts: all
  become: yes
  become_user: root
  roles:
        - geerlingguy.git
        - kfieldho.cmake
  tasks:
    - name: debian | Install packages
      package: pkg={{item}} state=installed
      with_items:
        - pkgconfig
        - libibverbs-dev
        - libbz2-dev
        - gfortran
        - liblapack-dev
        - nvidia-cuda-toolkit
        - xutils-dev
        - libx11-dev
        - flex
        - bison
        - libssl-dev
      when: ansible_os_family == 'Debian'
    - name: redhat | Install scl and devpackages
      package: pkg={{item}} state=latest
      with_items:
        - centos-release-scl
        - libibverbs-devel-static
        - flex
        - bison
        - openssl-devel
        - libX11-devel
        - rpm-build
        - libtool
        - zlib-devel
        - kernel-devel
        - numactl-devel
        - wget
        - imake
        - tcl-devel
        - gtest-devel
        - texlive-latex
        - ImageMagick
        - sqlite-devel
      when: ansible_os_family == 'RedHat'
    - name: Install cuda repo
      yum: state=present pkg=https://developer.nvidia.com/compute/cuda/8.0/prod/local_installers/cuda-repo-rhel6-8-0-local-8.0.44-1.x86_64-rpm
      when: ansible_os_family == 'RedHat'
    - name: redhat | Install devtoolset-4 and cuda
      package: pkg={{item}} state=latest
      with_items:
        - devtoolset-4-toolchain
        - cuda
      when: ansible_os_family == 'RedHat'
    - name: Download OFED 3.18-2
      get_url: url=http://downloads.openfabrics.org/OFED/ofed-3.18-2/OFED-3.18-2.tgz dest=/tmp/ofed.tgz
    - name: Create dir to untar to
      file: name=/tmp/ofed state=directory
    - name: Untar OFED
      unarchive: src=/tmp/ofed.tgz dest=/tmp/ofed/
    - name: redhat | Install OFED deps
      package: pkg={{item}} state=latest
      with_items:
        - libnl-devel
    - name: Install OFED
      command: /tmp/ofed/OFED-3.18/install.pl -q --basic --without-compat-rdma
    - name: Download MPSS installer
      get_url: url=http://registrationcenter-download.intel.com/akdlm/irc_nas/9226/mpss-3.7.1-linux.tar dest=/tmp/mpss.tar
    - name: Create dir for mpss
      file: name=/tmp/mpss state=directory
    - name: Untar MPSS
      unarchive: src=/tmp/mpss.tar dest=/tmp/mpss
    - name: Install MPSS packages
      yum: pkg={{item}} state=installed
      with_items:
        - /tmp/mpss/mpss-3.7.1/glibc2.12pkg-libmicaccesssdk0-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/glibc2.12pkg-libmicaccesssdk-dev-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/glibc2.12pkg-libmicmgmt0-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/glibc2.12pkg-libmicmgmt-dev-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/glibc2.12pkg-libmicmgmt-doc-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/glibc2.12pkg-libodmdebug0-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/glibc2.12pkg-libodmdebug-dev-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/glibc2.12pkg-libsettings0-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/glibc2.12pkg-libsettings-dev-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/glibc2.12pkg-mpss-flash-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/glibc2.12pkg-mpss-memdiag-kernel-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/glibc2.12pkg-mpss-rasmm-kernel-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/intel-composerxe-compat-k1om-3.7.1-1.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/libscif0-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/libscif-dev-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/libscif-doc-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-boot-files-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-coi-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-coi-dev-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-coi-doc-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-core-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-core-dev-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-daemon-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-daemon-dev-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-eclipse-cdt-mpm-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-license-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-miccheck-3.7.1-r1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-miccheck-bin-3.7.1-r1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-micmgmt-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-micmgmt-doc-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-micmgmt-python-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-micsmc-gui-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-modules-headers-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-mpm-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-mpm-doc-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-myo-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-myo-dev-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-myo-doc-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-offload-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-offload-dev-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-sciftutorials-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-sciftutorials-doc-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-sdk-k1om-3.7.1-1.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-sysmgmt-micdiagnostic-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-sysmgmt-micras-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/mpss-sysmgmt-python-3.7.1-1.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/netperf-2.6.0-r0.glibc2.12.x86_64.rpm
        - /tmp/mpss/mpss-3.7.1/netperf-doc-2.6.0-r0.glibc2.12.x86_64.rpm
    - name: Download intel installer
      get_url: url=http://packages.zenotech.com/parallel_studio_xe_2016_update3_online.sh dest=/tmp/intel_installer_online.sh mode=0755
    - name: Download silent.cfg
      get_url: url=http://packages.zenotech.com/silent.cfg dest=/tmp/silent.cfg mode=0644
    - name: Install intel toolset
      command: /tmp/intel_installer_online.sh --silent /tmp/silent.cfg
      tags: intel
