---
- include: harden.yml
- hosts: ci-build
  sudo: yes
  vars:
    - pip_version: 8.1.*
  pre_tasks:
    - name: "Update apt cache if needed"
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == 'Debian'

  roles:
        - geerlingguy.git
        - markwilde.gcc
        - azavea.pip
        - kfieldho.cmake
  tasks:
    - name: "Install packages"
      apt: pkg={{item}} state=installed
      with_items:
        - pkgconfig
        - libibverbs-dev
        - libbz2-dev
        - gfortran
        - liblapack-dev
        - nvidia-cuda-toolkit
        - xutils-dev
        - libx11-dev
        - flex
        - bison
        - libssl-dev
