---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Add dns search domain
      lineinfile: dest=/etc/dhcp/dhclient.conf state=present line='append domain-name " {{cluster_id}}.epic-cluster.zenotech.com"'