---
- hosts: all
  become: yes
  become_user: root
  tasks:
        - service: name=rpcbind state=started
        - mount: src={{nfs_master}}:/zdata name=/zdata state=mounted fstype=nfs
        - mount: src={{nfs_master}}:/zapps name=/zapps state=mounted fstype=nfs
