---
- include: slurm-common.yml
- hosts: all
  become: yes
  vars:
    pip_version: "8.1.*"
    slurm_master: "localhost"
    slurm_clustername: "{{ansible_hostname}}"
    slurm_dbdhost: "localhost"
    slurm_dbduser: "slurm"
    slurm_dbdpassword: "password"
    slurm_dbddb: "slurm"
    mysql_packages:
      - mariadb-client
      - mariadb-server
      - python-mysqldb
    mysql_user_home: /root
    mysql_root_password: root
    mysql_enabled_on_startup: yes
    mysql_users:
      - name: slurm
        host: "%"
        password: "password"
        priv: "*.*:ALL"
  pre_tasks:
    - name: "Update apt cache if needed"
      apt: update_cache=yes cache_valid_time=3600
      when: ansible_os_family == 'Debian'

  roles:
    - zenotech.mysql
    - { role: zenotech.slurm, is_slurm_master: true, is_slurm_node: false }

