---
- include: slurm-common.yml
- hosts: all
  become: yes
  become_user: root
  vars:
      pip_version: "8.1.*"
      slurm_master: "localhost"
      slurm_clustername: "default"
  roles:
      - { role: zenotech.slurm, is_slurm_master: false, is_slurm_node: true }
