# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 expandtab:

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu_aws"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    #aws.instance_type = "m4.large"
    aws.instance_type = "t2.micro"
    aws.keypair_name = ENV['AWS_KEYPAIR_NAME'] 
    aws.ami = "ami-f95ef58a"
    aws.region = "eu-west-1"
    aws.subnet_id = "subnet-be5460db"
    aws.tags = {
      'Name' => 'SoftwareDevBastion',
      'client' => 'client'
    }
    aws.security_groups = ['sg-8c0db7e8']
    aws.associate_public_ip = true

    aws.region_config "eu-west-1" do |region|
        region.spot_instance = true
        region.spot_max_price = "0.03"
    end

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = ENV['MY_PRIVATE_AWS_SSH_KEY_PATH']
  end

  # Provision
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/main.yml"
  end
end

