---
- hosts: all

  vars:
    celery_dir: "/opt/app"
    celery_start_on: "vagrant-mounted"
    celery_autoreload: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  tasks:
    - name: Install demoapp requirements
      pip: chdir="{{ celery_dir }}" requirements=requirements.txt

  roles:
    - { role: "azavea.redis" }
    - { role: "azavea.celery" }
